### ISSUE TITLE
gjamOrdination.Rd

### ISSUE THREAD

**Issue by BertvanderVeen** [cran/gjam#1]
Under "details" the documentation for `gjamOrdination` reads:

_\details{
 Ordinates the response correlation \code{ematrix} contained in \code{output$parameterTables}.  If \code{method = 'PCA'} returns eigenvalues and eigenvectors.  If \code{method = 'PCA'} returns three NMDS dimensions.  If \code{PLOT}, then plots will be generated.  Uses principle components analysis or non-metric multidimensional scale (NMDS).
}_

where supposedly the second \code{method = 'PCA'}  should read \code{method = 'NMDS'}.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
